language: cpp
sudo: true
compiler:
  - clang

os:
  - linux
  - osx
  - windows

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./travis-clang.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./travis-clang.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then ./travis-cl.sh; fi
